version: "3"
services:

  selenium-hub:
    image: selenium/hub:3.141.59-zinc
    ports:
      - "4444:4444"
    environment:
      GRID_MAX_SESSION: 16
      GRID_BROWSER_TIMEOUT: 300
      GRID_TIMEOUT: 300

  chrome:
    image: selenium/node-chrome:3.141.59-zinc
    depends_on:
      - selenium-hub
    environment:
      HUB_HOST: selenium-hub
      HUB_PORT: 4444
      NODE_MAX_SESSION: 2
      NODE_MAX_INSTANCES: 2